### ISSUE TITLE
Error when trying to load

### ISSUE THREAD

**Issue by angiioh** [catppuccin/chrome-devtools#5]
Hi! I just tried this out, but I'm running into an error when I try to load the unpacked extension. 

**Chrome error:**
Failed to load extension
File
~\Documents\Rice\chrome-devtools-main\themes\mocha_mauve
Error
Could not load icon 'images/icon16.png' specified in 'icons'.
Could not load manifest.

**Comment by r58Playz** [comment]
Are you on windows? This looks like an issue with symbolic links not being created. A fresh clone loads fine on my end.

**Comment by angiioh** [comment]
Thanks for your reply! Yep, I'm on Windows. I extracted the file via running 7zip as an admin. Is there something I should be doing instead?

**Comment by srshah27** [comment]
Yes, using `-c core.symlinks=true` in admin shell works fine.
