### ISSUE TITLE
Not Applying Theme

### ISSUE THREAD

**Issue by novafurry** [catppuccin/chrome-devtools#6]
Hi. I have installed the theme, and moved all files from template to the  actual plugins folder, enabled custom stylesheets and it does not function (Catppuccin Frappe Pink btw)
<details><summary>See Screenshots</summary>
<p>
![image](https://github.com/user-attachments/assets/cea29376-2b4a-40ee-9e64-d933c8cbc6b0)
![image](https://github.com/user-attachments/assets/14d6bd5e-45b8-4e6f-b752-898bab981ba8)
![image](https://github.com/user-attachments/assets/4c8c02da-1581-4666-9b1c-5cbf57cf4072)

</p>
</details> 

U/A String:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
I am on the Dev(Unstable) Chrome build on Arch Linux.
I have reloaded Devtools and Restarted chrome.

**Comment by uncenter** [comment]
What does "moved all files from template to the actual plugins folder" mean? That isn't an installation step.

**Comment by r58Playz** [comment]
Also note that the theme will not load on protected URLs like `chrome://*`, nor will it show up in the theme selector.

![image](https://github.com/user-attachments/assets/d455c8b2-b718-4b20-ad65-eb8c02cb98e9)

**Comment by novafurry** [comment]
Ohh, that must've been it, i *was * testing it on the extensions page.
By "moved all files from template to plugin folder" i meant to move the
files that were meant to be symlinked over the symlink
